#! /bin/sh
#
# Example panel for LemonBoy's bar

logo="\\f7  \\f9 kreator"
while read -r line ; do
	case $line in
	S*)
		sys_infos="\\r${line#?}\\fr"
	;;
	T*)
		title="\\br\\f7 ${line#?} \\f9"
	;;
	W*)
		wm_infos=""
		IFS=':'
		set -- ${line#?}
		while [ $# -gt 0 ] ; do
			item=$1
			name=${item#?}
			case $item in
			[OFU]*)
				# active desktop
				wm_infos="$wm_infos\\f9 • \\fr\\br"
			;;
			o*)
				# inactive but occupied desktop
				wm_infos="$wm_infos\\f8 • \\fr"
			;;
			f*)
				# inactive desktop
				wm_infos="$wm_infos\\f8 ○ \\fr"
			;;
			u*)
				# urgent desktop
				wm_infos="$wm_infos \\f3•\\fr "
			;;
			L*)
				# layout
				#layout=$(printf "%s" "${name}" | sed 's/\(.\).*/\U\1/')
				layout=""
				wm_infos="$wm_infos \\b4\\f0$layout\\br\\fr"
			;;
			esac
			shift
		done
	;;
	esac
	printf "%s\n" "$logo $wm_infos $title $sys_infos"
done
