#! /bin/sh
#
# Example panel for LemonBoy's bar

logo="\\f7\\aa  \\f9 $(hostname -s)\aZ"
while read -r line ; do
	case $line in
	S*)
		sys_infos="\\r${line#?}\\fr"
	;;
	T*)
		title="\\br\\f7 ${line#?} \\f9"
	;;
	W*)
		wm_infos=""
		IFS=':'
		set -- ${line#?}
		while [ $# -gt 0 ] ; do
			item=$1
			name=${item#?}
			case $item in
			[OFU]*)
				# active desktop
				wm_infos="$wm_infos\\a${name}\\f9 • \\fr\\aZ"
			;;
			o*)
				# inactive but occupied desktop
				wm_infos="$wm_infos\\a${name}\\f8 • \\fr\\aZ"
			;;
			f*)
				# inactive desktop
				wm_infos="$wm_infos\\a${name}\\f8 ○ \\fr\\aZ"
			;;
			u*)
				# urgent desktop
				wm_infos="$wm_infos\\a${name}\\f3 • \\fr\\aZ"
			;;
			L*)
				# layout
				case $name in
				t*)
					layout=""
				;;
				m*)
					layout=""
				;;
				esac
				wm_infos="$wm_infos \\al\\f7$layout\\aZ"
			;;
			esac
			shift
		done
	;;
	esac
	printf "%s\n" "$logo $wm_infos $title $sys_infos"
done
