#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width		2
bspc config window_gap			10
bspc config top_padding			15
bspc config split_ratio			0.50
bspc config borderless_monocle		true
bspc config gapless_monocle		true
bspc config focus_follows_pointer	true
bspc config auto_alternate		true
bspc config auto_cancel			true

bspc rule -a Chromium desktop=^9
bspc rule -a 'class=="Skype"' 'floating=on'
bspc rule -a 'class=="Pidgin"' 'floating=on'

rm -f $PANEL_FIFO
mkfifo $PANEL_FIFO
~/.config/bspwm/panel/panel &
