#! /bin/sh

bspc monitor -d b c d e f g h i j k

bspc config border_width		2
bspc config window_gap			5
bspc config top_padding			20
bspc config split_ratio			0.50
bspc config focus_follows_pointer	true
bspc config auto_alternate		true
bspc config auto_cancel			true
bspc config history_aware_focus		true

bspc rule -a Chromium 'desktop=^9'
bspc rule -a Skype 'floating=on'
bspc rule -a Pidgin 'floating=on'

rm -f $PANEL_FIFO
mkfifo $PANEL_FIFO
~/.config/bspwm/panel/panel &
